modLoader="javafml"
loaderVersion="[43,)"
license="Microsoft Reciprocal License (Ms-RL)"

[[mods]]
modId="elementalpowers"
version="2.0.0"
displayName="ElementalPowers"
credits="Made by bilbikdoci"
displayURL="https://www.curseforge.com/minecraft/mc-mods/elemental-powers/files"
logoFile="logo.png"
authors="Bilbikdoci"

[[dependencies.elementalpowers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




