configVersion: 4
baseHead: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWRiNTMyYjVjY2VkNDZiNGI1MzVlY2UxNmVjZWQ3YmJjNWNhYzU1NTk0ZDYxZThiOGY4ZWFjNDI5OWM5ZmMifX19
baseHeadRecipe:
  - 'PPP'
  - 'PPP'
  - 'PPP'
recipeMaterials:
  P:
    - OAK_PLANKS
    - BIRCH_PLANKS
    - SPRUCE_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - MANGROVE_PLANKS
    - CRIMSON_PLANKS
    - WARPED_PLANKS
    - CHERRY_PLANKS
  S:
    - OAK_SLAB
    - BIRCH_SLAB
    - SPRUCE_SLAB
    - JUNGLE_SLAB
    - ACACIA_SLAB
    - DARK_OAK_SLAB
    - DARK_OAK_SLAB
    - MANGROVE_SLAB
    - CRIMSON_SLAB
    - WARPED_SLAB
    - CHERRY_SLAB
  F:
    - OAK_FENCE
    - BIRCH_FENCE
    - SPRUCE_FENCE
    - JUNGLE_FENCE
    - ACACIA_FENCE
    - DARK_OAK_FENCE
    - DARK_OAK_FENCE
    - MANGROVE_FENCE
    - CRIMSON_FENCE
    - WARPED_FENCE
    - CHERRY_FENCE
  alternateBlocksIngredient: REDSTONE_TORCH