modLoader = "javafml" #mandatory`
loaderVersion = "[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/iron431/Irons-Spells-n-Spellbooks/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId = "irons_spellbooks" #mandatory
version = "1.21-3.8.5" #mandatory
displayName = "Iron's Spells 'n Spellbooks" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks" #optional
logoFile = "spellbooks title small background low res.png" #optional
credits = '''
  Crispytwig: Various Jewelry textures and Cloth textures
  Crydigo: Ink, Spellbook, Mithril, Hogskin, and Dragonskin textures; Priest Armor and Dead King models
  Cakeman: Spellbook models
  Bodya33381: Scroll textures
  RenovatedStudios: Various spell icons
  Caner Crebes: Dead King boss music
  Amo: Spellbook Apotheosis compat
  Some assets remixed from J. W. Bjerk (eleazzaar)'s Painterly Spell Icon Packs -- www.jwbjerk.com/art  -- find this and other open art at: http://opengameart.org.''' #optional
authors = "Iron431, Lab3" #optional
description = '''A magic mod for Minecraft returning to the classic RPG spellcasting fantasy.'''
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config = "irons_spellbooks.mixins.json"
[[accessTransformers]]
## The file is relative to the output directory of the resources, or the root path inside the jar when compiled
## The 'resources' directory represents the root output directory of the resources
file="META-INF/accesstransformer.cfg"

[[dependencies.irons_spellbooks]] #optional
# the modid of the dependency
modId="neoforge" #mandatory
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
# 'required' requires the mod to exist, 'optional' does not
# 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
type="required" #mandatory
# Optional field describing why the dependency is required or why it is incompatible
# reason="..."
# The version range of the dependency
versionRange="[21.0.0-beta,)" #mandatory
# An ordering relationship for the dependency.
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

# Here's another dependency
[[dependencies.irons_spellbooks]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.21,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.irons_spellbooks]]
modId="geckolib"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[4.5.8,)"
ordering="NONE"
side="BOTH"

[[dependencies.irons_spellbooks]]
modId="playeranimator"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[2.0.0-alpha1+1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.irons_spellbooks]]
modId="playeranimator"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[2.0.0-alpha1+1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.irons_spellbooks]]
modId="curios"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[9.0.5+1.21.0,)"
ordering="NONE"
side="BOTH"